// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.1
// source: l2orderbook.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type L2OrderBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Size     uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Interval uint32 `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *L2OrderBookRequest) Reset() {
	*x = L2OrderBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2orderbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2OrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2OrderBookRequest) ProtoMessage() {}

func (x *L2OrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2orderbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2OrderBookRequest.ProtoReflect.Descriptor instead.
func (*L2OrderBookRequest) Descriptor() ([]byte, []int) {
	return file_l2orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *L2OrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *L2OrderBookRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *L2OrderBookRequest) GetInterval() uint32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type L2OrderBookItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume uint64 `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *L2OrderBookItem) Reset() {
	*x = L2OrderBookItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2orderbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2OrderBookItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2OrderBookItem) ProtoMessage() {}

func (x *L2OrderBookItem) ProtoReflect() protoreflect.Message {
	mi := &file_l2orderbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2OrderBookItem.ProtoReflect.Descriptor instead.
func (*L2OrderBookItem) Descriptor() ([]byte, []int) {
	return file_l2orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *L2OrderBookItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *L2OrderBookItem) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type L2OrderBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string               `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bid    []*L2OrderBookItem   `protobuf:"bytes,2,rep,name=bid,proto3" json:"bid,omitempty"`
	Ack    []*L2OrderBookItem   `protobuf:"bytes,3,rep,name=ack,proto3" json:"ack,omitempty"`
	Time   *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *L2OrderBook) Reset() {
	*x = L2OrderBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2orderbook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2OrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2OrderBook) ProtoMessage() {}

func (x *L2OrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_l2orderbook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2OrderBook.ProtoReflect.Descriptor instead.
func (*L2OrderBook) Descriptor() ([]byte, []int) {
	return file_l2orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *L2OrderBook) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *L2OrderBook) GetBid() []*L2OrderBookItem {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *L2OrderBook) GetAck() []*L2OrderBookItem {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *L2OrderBook) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_l2orderbook_proto protoreflect.FileDescriptor

var file_l2orderbook_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x32, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x12, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x22, 0x3f, 0x0a, 0x0f, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f,
	0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x22, 0x0a, 0x03, 0x62,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4c, 0x32, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12,
	0x22, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4c,
	0x32, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x03,
	0x61, 0x63, 0x6b, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x32, 0x44, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b,
	0x12, 0x37, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x13, 0x2e, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x4c, 0x32, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_l2orderbook_proto_rawDescOnce sync.Once
	file_l2orderbook_proto_rawDescData = file_l2orderbook_proto_rawDesc
)

func file_l2orderbook_proto_rawDescGZIP() []byte {
	file_l2orderbook_proto_rawDescOnce.Do(func() {
		file_l2orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_l2orderbook_proto_rawDescData)
	})
	return file_l2orderbook_proto_rawDescData
}

var file_l2orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_l2orderbook_proto_goTypes = []interface{}{
	(*L2OrderBookRequest)(nil),  // 0: L2OrderBookRequest
	(*L2OrderBookItem)(nil),     // 1: L2OrderBookItem
	(*L2OrderBook)(nil),         // 2: L2OrderBook
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_l2orderbook_proto_depIdxs = []int32{
	1, // 0: L2OrderBook.bid:type_name -> L2OrderBookItem
	1, // 1: L2OrderBook.ack:type_name -> L2OrderBookItem
	3, // 2: L2OrderBook.time:type_name -> google.protobuf.Timestamp
	0, // 3: OrderBook.GetL2OrderBook:input_type -> L2OrderBookRequest
	2, // 4: OrderBook.GetL2OrderBook:output_type -> L2OrderBook
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_l2orderbook_proto_init() }
func file_l2orderbook_proto_init() {
	if File_l2orderbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_l2orderbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2OrderBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2orderbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2OrderBookItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2orderbook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2OrderBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_l2orderbook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_l2orderbook_proto_goTypes,
		DependencyIndexes: file_l2orderbook_proto_depIdxs,
		MessageInfos:      file_l2orderbook_proto_msgTypes,
	}.Build()
	File_l2orderbook_proto = out.File
	file_l2orderbook_proto_rawDesc = nil
	file_l2orderbook_proto_goTypes = nil
	file_l2orderbook_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderBookClient is the client API for OrderBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderBookClient interface {
	GetL2OrderBook(ctx context.Context, in *L2OrderBookRequest, opts ...grpc.CallOption) (OrderBook_GetL2OrderBookClient, error)
}

type orderBookClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderBookClient(cc grpc.ClientConnInterface) OrderBookClient {
	return &orderBookClient{cc}
}

func (c *orderBookClient) GetL2OrderBook(ctx context.Context, in *L2OrderBookRequest, opts ...grpc.CallOption) (OrderBook_GetL2OrderBookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderBook_serviceDesc.Streams[0], "/OrderBook/GetL2OrderBook", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderBookGetL2OrderBookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderBook_GetL2OrderBookClient interface {
	Recv() (*L2OrderBook, error)
	grpc.ClientStream
}

type orderBookGetL2OrderBookClient struct {
	grpc.ClientStream
}

func (x *orderBookGetL2OrderBookClient) Recv() (*L2OrderBook, error) {
	m := new(L2OrderBook)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderBookServer is the server API for OrderBook service.
type OrderBookServer interface {
	GetL2OrderBook(*L2OrderBookRequest, OrderBook_GetL2OrderBookServer) error
}

// UnimplementedOrderBookServer can be embedded to have forward compatible implementations.
type UnimplementedOrderBookServer struct {
}

func (*UnimplementedOrderBookServer) GetL2OrderBook(*L2OrderBookRequest, OrderBook_GetL2OrderBookServer) error {
	return status.Errorf(codes.Unimplemented, "method GetL2OrderBook not implemented")
}

func RegisterOrderBookServer(s *grpc.Server, srv OrderBookServer) {
	s.RegisterService(&_OrderBook_serviceDesc, srv)
}

func _OrderBook_GetL2OrderBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(L2OrderBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookServer).GetL2OrderBook(m, &orderBookGetL2OrderBookServer{stream})
}

type OrderBook_GetL2OrderBookServer interface {
	Send(*L2OrderBook) error
	grpc.ServerStream
}

type orderBookGetL2OrderBookServer struct {
	grpc.ServerStream
}

func (x *orderBookGetL2OrderBookServer) Send(m *L2OrderBook) error {
	return x.ServerStream.SendMsg(m)
}

var _OrderBook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OrderBook",
	HandlerType: (*OrderBookServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetL2OrderBook",
			Handler:       _OrderBook_GetL2OrderBook_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "l2orderbook.proto",
}
